development:
  directory: 'fcwindsochidev'
  access_key_id: 'AKIAIBBHB37TCVCYD7FQ'
  secret_access_key: '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'

test:
  <<: *development

production:
  directory: 'fcwindsochieu'
  access_key_id: 'AKIAIBBHB37TCVCYD7FQ'
  secret_access_key: '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'
