development:
  s3_direct:         <%= ENV['S3_DIRECT'] %>
  s3_key:            <%= ENV['S3_KEY'] %>
  s3_secret:         <%= ENV['S3_SECRET'] %>
  s3_region:         <%= ENV['S3_REGION'] %>

  github_key:        <%= ENV['GITHUB_KEY'] %>
  github_secret:     <%= ENV['GITHUB_SECRET'] %>
  github_callback:   <%= ENV['GITHUB_CALLBACK'] %>

  twitter_key:       <%= ENV['TWITTER_KEY'] %>
  twitter_secret:    <%= ENV['TWITTER_SECRET'] %>
  twitter_callback:  <%= ENV['TWITTER_CALLBACK'] %>

  facebook_key:      <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret:   <%= ENV['FACEBOOK_SECRET'] %>
  facebook_callback: <%= ENV['FACEBOOK_CALLBACK'] %>

production:
  s3_direct:         <%= ENV['S3_DIRECT'] %>
  s3_key:            <%= ENV['S3_KEY'] %>
  s3_secret:         <%= ENV['S3_SECRET'] %>
  s3_region:         <%= ENV['S3_REGION'] %>

  github_key:        <%= ENV['GITHUB_KEY'] %>
  github_secret:     <%= ENV['GITHUB_SECRET'] %>
  github_callback:   <%= ENV['GITHUB_CALLBACK'] %>

  twitter_key:       <%= ENV['TWITTER_KEY'] %>
  twitter_secret:    <%= ENV['TWITTER_SECRET'] %>
  twitter_callback:  <%= ENV['TWITTER_CALLBACK'] %>

  facebook_key:      <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret:   <%= ENV['FACEBOOK_SECRET'] %>
  facebook_callback: <%= ENV['FACEBOOK_CALLBACK'] %>

test:
  s3_direct:         <%= ENV['S3_DIRECT'] %>
  s3_key:            <%= ENV['S3_KEY'] %>
  s3_secret:         <%= ENV['S3_SECRET'] %>
  s3_region:         <%= ENV['S3_REGION'] %>

  github_key:        <%= ENV['GITHUB_KEY'] %>
  github_secret:     <%= ENV['GITHUB_SECRET'] %>
  github_callback:   <%= ENV['GITHUB_CALLBACK'] %>

  twitter_key:       <%= ENV['TWITTER_KEY'] %>
  twitter_secret:    <%= ENV['TWITTER_SECRET'] %>
  twitter_callback:  <%= ENV['TWITTER_CALLBACK'] %>

  facebook_key:      <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret:   <%= ENV['FACEBOOK_SECRET'] %>
  facebook_callback: <%= ENV['FACEBOOK_CALLBACK'] %>
